"""Added users and spammers tables

Revision ID: 7a2cbd5903c8
Revises: 
Create Date: 2021-05-10 23:22:13.896769

"""
from alembic import op
import sqlalchemy as sa

from schemas.spammer import SpammerStateEnum

# revision identifiers, used by Alembic.
revision = '7a2cbd5903c8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    spammer_type_enum = sa.Enum(
        SpammerStateEnum,
        name='spammer_type_enum'
    )
    # spammer_type_enum.create(op.get_bind())

    op.create_table('spammer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('target', sa.String(), nullable=True),
    # sa.Column('state', sa.Enum('idle', 'working', 'stopped', name='spammerstateenum'), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(
        'spammer', 
        sa.Column("state", spammer_type_enum,
        default=SpammerStateEnum.idle
    ))

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('hashed_password')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('spammer')
    # ### end Alembic commands ###
