"""empty message

Revision ID: 8c9aed12e2be
Revises: e9010519dd3d
Create Date: 2021-08-21 11:12:11.376689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c9aed12e2be'
down_revision = 'e9010519dd3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
