"""empty message

Revision ID: f0d5915490c7
Revises: 6bd449e01e71
Create Date: 2021-07-07 20:40:15.481065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0d5915490c7'
down_revision = '6bd449e01e71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spammer', 'target')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spammer', sa.Column('target', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
