"""empty message

Revision ID: e9010519dd3d
Revises: 9a167f3f2ced
Create Date: 2021-08-20 07:35:53.611674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9010519dd3d'
down_revision = '9a167f3f2ced'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
